### ISSUE TITLE
Posting raster with specific SLD file fails.

### ISSUE THREAD

**Issue by jirik** [LayerManager/layman#681]
Posting `sample_tif_grayscale_alpha_nodata.tif` with specific SLD style fails.

Style:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0" xmlns:sld="http://www.opengis.net/sld">
  <UserLayer>
    <sld:LayerFeatureConstraints>
      <sld:FeatureTypeConstraint/>
    </sld:LayerFeatureConstraints>
    <sld:UserStyle>
      <sld:Name>sample_tif_grayscale_alpha_nodata</sld:Name>
      <sld:FeatureTypeStyle>
        <sld:Rule>
          <sld:RasterSymbolizer>
            <sld:ChannelSelection>
              <sld:GrayChannel>
                <sld:SourceChannelName>1</sld:SourceChannelName>
                <sld:ContrastEnhancement>
                  <sld:Normalize>
                    <sld:VendorOption name="algorithm">StretchToMinimumMaximum</sld:VendorOption>
                    <sld:VendorOption name="minValue">-0.00943396</sld:VendorOption>
                    <sld:VendorOption name="maxValue">0.912477</sld:VendorOption>
                  </sld:Normalize>
                </sld:ContrastEnhancement>
              </sld:GrayChannel>
            </sld:ChannelSelection>
            <sld:ColorMap>
              <sld:ColorMapEntry quantity="0" color="#000000"/>
              <sld:ColorMapEntry quantity="255" color="#ffffff"/>
            </sld:ColorMap>
          </sld:RasterSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </UserLayer>
</StyledLayerDescriptor>
```

Exception:
```
[2022-10-24 11:08:39,602: INFO/ForkPoolWorker-1] PRE task=layman.layer.filesystem.thumbnail.refresh, workspace=dynamic_test_workspace_layer_style, publication_name=layer_tif_byte_post
[2022-10-24 11:08:40,266] INFO in rest_workspace_layer: GET Layer, actor=None
172.18.0.11 - - [24/Oct/2022 11:08:40] "GET /rest/workspaces/dynamic_test_workspace_layer_style/layers/layer_tif_byte_post HTTP/1.1" 200 -
[2022-10-24 11:08:40,467: ERROR/ForkPoolWorker-1] Task layman.layer.filesystem.thumbnail.refresh[71f49df7-69bb-4cbe-96c4-ea529527fb67] raised unexpected: LaymanError('Thumbnail rendering failed')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/src/layman/make_celery.py", line 36, in __call__
    return self.run(*args, **kwargs)
  File "/code/src/layman/layer/filesystem/tasks.py", line 148, in refresh_thumbnail
    thumbnail.generate_layer_thumbnail(workspace, layername)
  File "/code/src/layman/layer/filesystem/thumbnail.py", line 92, in generate_layer_thumbnail
    raise LaymanError("Thumbnail rendering failed", data=response.content)
layman.http.LaymanError: LaymanError code=-1 message=Thumbnail rendering failed data=b'<?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://localhost:8000/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException>\n      java.lang.NullPointerException\n</ServiceException></ServiceExceptionReport>' private_info=None

```

**Comment by jirik** [comment]
SLD seems valid. It seems to be bug of GeoServer, maybe related to version 2.15. However, GeoServer gives us no interesting clue:
```
24-Oct-2022 11:33:28.735 INFO [http-nio-8080-exec-10] org.geoserver.GeoserverInitStartupListener$1.errorOccurred Problem occurs when computing a tile by the owner.
 java.lang.NullPointerException
	at javax.media.jai.PlanarImage.copyData(PlanarImage.java:2344)
	at javax.media.jai.PlanarImage.copyExtendedData(PlanarImage.java:2398)
...
```

**Comment by jirik** [comment]
Maybe related:
- https://stackoverflow.com/a/43638143/5259610
- https://forum.step.esa.int/t/snap-temporal-percentile-operator-test-case-failed/15701/9
- https://sourceforge.net/p/geoserver/mailman/geoserver-users/thread/ad4daada411a4aaca6e855ceeeca6b04%40C119S212VM042.msvyvi.vaha.local/#msg36945132

**Comment by jirik** [comment]
Example of SLD that publishes successfully:
```
<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name>name</sld:Name>
    <sld:UserStyle>
      <sld:Name>name</sld:Name>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Rule>
          <sld:RasterSymbolizer>
            <sld:ColorMap>
              
              <sld:ColorMapEntry color="#000000" quantity="-0.009433962404727936"/>
              <sld:ColorMapEntry color="#ffffff" quantity="0.9124773740768433"/>
              
            </sld:ColorMap>
            <sld:ContrastEnhancement/>
          </sld:RasterSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>

```

**Comment by index-git** [comment]
Removing Alfa channel solves the problem. On GS 2.21 completely, on GS 2.15 with black surroundings of the image (instead of the transparent part).

**Comment by jirik** [comment]
Also, in 2.15 there is still issue with some failing WMS requests (e.g. the one for thumbnail). In 2.21 there are no such issues.

**Comment by jirik** [comment]
Implemented by GeoServer upgrade.
