### ISSUE TITLE
Publishing layer from external DB with QML

### ISSUE THREAD

**Issue by jirik** [LayerManager/layman#818]
```
Traceback (most recent call last):
  File "/code/src/layman/layer/db/__init__.py", line 589, in get_geometry_types
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "wkb_geometry" does not exist
LINE 2:     select distinct ST_GeometryType("wkb_geometry") as geome...
                                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/src/layman/make_celery.py", line 36, in __call__
    return self.run(*args, **kwargs)
  File "/code/src/layman/layer/qgis/tasks.py", line 29, in refresh_wms
    wms.save_qgs_file(workspace, layername)
  File "/code/src/layman/layer/qgis/wms.py", line 76, in save_qgs_file
    db_types = db.get_geometry_types(db_schema, table_name, conn_cur=conn_cur)
  File "/code/src/layman/layer/db/__init__.py", line 592, in get_geometry_types
    raise LaymanError(7) from exc
layman.http.LaymanError: LaymanError code=7 message=Database query error data=None private_info=None
```

**Comment by jirik** [comment]
Forgot to pass column name
```
https://github.com/LayerManager/layman/blob/ff44d76b5173a89834d9291ec9f5859799f3fbd5/src/layman/layer/qgis/wms.py#L76
```
